name: E2E

on: [push]

jobs:
  main:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18]

    name: Node ${{ matrix.node }} E2E

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"
      - uses: nrwl/nx-set-shas@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - run: pnpm install
      - run: sudo apt-get install -y expect
      - run: npx playwright install --with-deps
      - name: Run tests
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          TERM: xterm # fix for tput tty issue
        run: npx nx run-many --target=e2e
