name: E2E Template

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18]

    name: Node ${{ matrix.node }} test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run tests
        run: npx nx e2e template-e2e
