name: E2E CLI

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 16, 18 ]

    name: Node ${{ matrix.node }} test

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install expect
        run: sudo apt-get install -y expect
      - name: Run tests
        working-directory: packages/cli/e2e
        run: ./bats/bin/bats test.bats
